apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx-black
  name: nginx-black
  namespace: obs
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx-black
  template:
    metadata:
      labels:
        run: nginx-black
    spec:
      volumes:
      - name: webdata
        emptyDir: {}
      initContainers:
      - name: web-content
        image: busybox
        volumeMounts:
        - name: webdata
          mountPath: "/webdata"
        command: ["/bin/sh", "-c", 'echo "<h1>I am <font color=black>black</font></h1>" > /webdata/index.html']
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: webdata
          mountPath: "/usr/share/nginx/html"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx-black
  name: nginx-black
  namespace: obs
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-black
  type: LoadBalancer
